### ISSUE TITLE
Relax `requests` version requirement to avoid crashing Certbot snap

### ISSUE THREAD

**Issue by alexzorin** [infinityofspace/certbot_dns_duckdns#117]
**Describe the bug**
This plugin requires `requests ~= 2.28` but the currently released version of Certbot ships with `requests` `2.27.1`.

The version incompatibility results in the crash reported at https://community.letsencrypt.org/t/certbot-running-error/183105.

**To Reproduce**
Install the Certbot snap, install this plugin snap, connect the plugin, and run `certbot plugins`.

**Expected behavior**
It should not crash.

**Versions (please complete the following version information):**
 - certbot: 1.29.0
 - certbot_dns_duckdns: 1.0

**Additional context**
Because it makes no sense to install this without Certbot and Certbot already specifies a version constraint for `requests`, I think the `requests` dependency could be relaxed here, perhaps just `>=2.0,<3.0`.

It would be greatly appreciated if a new version of this plugin could be published on snap, as it is broken for users at the moment. Thank you for your work.

**Comment by infinityofspace** [comment]
Thanks for your bug report.

Installing the plugin without certbot as snap versions due the version requirement issue makes no sense as you already described.
I will adjust all requirements accordingly. Also I try to add a small test for the snap version for the CI, so that such a problem should no longer occur.
