### ISSUE TITLE
GUIDENS wanted

### ISSUE THREAD

**Issue by gamingoninsulin** [infinityofspace/certbot_dns_duckdns#129]
**Describe the bug**
i think its not realy but but i think do someting stuppid tho 
i am trying to install certbot-dns-duckdns formt here but with no luck i am able to install tho but when its done i do certbot plugins to check the list i only get

* nginx
* standalone
* webroot

 i have installed snapd aswell and installed the rest trough docker it self
can you help me pin point the error ( i use the ubuntu 22.04 as adminuser thats the name i gave the account while installing ubuntu 22.04)

oh and i got if i trust the certbot-dns-duckdns packge i needed to do this "snap set certbot trust-plugin-with-root=ok" so i did
i also did just know a remove and reinstalled the certbot-dns-duckdns packge

please help me xD i have no clue on what to do!!

**Comment by infinityofspace** [comment]
> i have installed snapd aswell and installed the rest trough docker it self

I don't quite understand how you installed certbot and the plugin. Did you install both as snap package or one with snap and the other as Docker container? Later on it appears that you installed both with snap, but at this point I'm unsure which installation method you used.

> i am trying to install certbot-dns-duckdns formt here but with no luck i am able to install tho but when its done i do certbot plugins to check the list i only get
> 
>     nginx
>     standalone
>     webroot

Correct, if it is not listed as output from the certbot plugins command, then it is not installed or there was a problem installing it.

>  i needed to do this "snap set certbot trust-plugin-with-root=ok" so i did

This is normal and the correct ways, because you have installed cerbot as a "global" snap package and therefore the plugin can be used here.

---

To debug the problem and find a solution I need more information. So please answer the following questions:

- What is the output of `which certbot` and `sudo which certbot`?
- What version is certbot and certbot_dns_duckdns? use `snap list`
- What is the output of the commands `snap install certbot-dns-duckdns` and `sudo snap connect certbot:plugin certbot-dns-duckdns`
- What is the output of `certbot plugins` when you install some other plugin like `certbot-dns-cloudflare`?
