### ISSUE TITLE
Use this extension with nginx

### ISSUE THREAD

**Issue by rambip** [infinityofspace/certbot_dns_duckdns#17]
I'm looking for a way to host a https website with nginx and with a dns from duck-dns.

Is there a way to do it ?

When I try to use the example command with `nginx`, it gives me this error:

```
Too many flags setting configurators/installers/authenticators 'dns-duckdns' -> 'nginx'
```

Is this the right tool to do what I want to do ?
And if yes what is the right way to do it ?

**Comment by infinityofspace** [comment]
I need more information which exact command and which versions of the plugin and certbot you used. Please fill out the issue template.

**Comment by rambip** [comment]
I found the right way to do it, I created the certificate with my duckdns token and then added it manually to my nginx config.
I just wonder why it is impossible to use the 2 flags `--nginx` and `--authenticator dns-duckdns`

The command I used was:
```
certbot certonly \
  --non-interactive \
  --agree-tos \
  --preferred-challenges dns \
  --authenticator dns-duckdns \
  --duck-dns-token $my_token
  -d "rambi.duckdns.org"
```
And I don't think this is specific to my version (I installed the latest version of certbot and certbot_dns_duckdns with pip)

**Comment by infinityofspace** [comment]
If you use the argument `--nginx` and `--authenticator dns-duckdns`, then you say certbot it should create a HTTP-01 challenge with nginx and a DNS-01 challenge with duckdns at the same time. This is logically not possible, because both are mutually exclusive. You can find more information about the different challenge types on the [letsencrypt page](https://letsencrypt.org/docs/challenge-types/).

From the [official docs](https://certbot.eff.org/docs/using.html#certbot-command-line-options):
```commandline
--nginx           Use the Nginx plugin for authentication & installation
```

And for [authenticator](https://certbot.eff.org/docs/using.html#certbot-command-line-options) plugins:
```
-a AUTHENTICATOR, --authenticator AUTHENTICATOR
                        Authenticator plugin name.
```

You can not combine multiple authenticators. You can combine only installer and authenticator, this is it also described [here](https://certbot.eff.org/docs/using.html#combination)

For more information about certbot please refer to the [official documentation](https://certbot.eff.org/docs/using.html).
If you need support for using certbot and this is not related to this DNS plugin, then use the official certbot [help channels](https://certbot.eff.org/help/).

_I will close the ticket as this is not a feature idea, an issue or related to this specific DNS plugin and relates only to the general use of certbot._

---

If you find a bug in `certbot_dns_duckdns` or have a feature idea then feel free to open a new issue and fill out the templates.
