### ISSUE TITLE
Plugin not recognised

### ISSUE THREAD

**Issue by tescophil** [infinityofspace/certbot_dns_duckdns#2]
Hi, I have certbot 0.31.0 installed and installed the plugin using pip3.

```
phil@marvin:~/wildcard_ssl$ certbot --version
certbot 0.31.0
phil@marvin:~/wildcard_ssl$ pip3 show certbot-dns-duckdns
Name: certbot-dns-duckdns
Version: 0.2
Summary: Obtain certificates using a DNS TXT record for DuckDNS domains
Home-page: https://github.com/infinityofspace/certbot_dns_duckdns
Author: infinityofspace
Author-email: None
License: MIT
Location: /usr/local/lib/python3.7/dist-packages
Requires: requests, zope.interface, certbot, setuptools
Required-by: 
phil@marvin:~/wildcard_ssl$ 
```

However, when I run a command to get a wildcard cert, certbot does not recognise the --dns-duckdns-token or --dns-duckdns-propagation-seconds directives on the command line:

```
phil@marvin:~/wildcard_ssl$ ./get_cert.sh 
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: --dns-duckdns-token <mytoken> --dns-duckdns-propagation-seconds 60
```

get_cert.sh:
```
certbot certonly \
  --non-interactive \
  --agree-tos \
  --email my-email@gmail.com \
  --preferred-challenges dns \
  --authenticator dns-duckdns \
  --dns-duckdns-token <my-token> \
  --dns-duckdns-propagation-seconds 60 \
  -d "*.my-site.duckdns.org"
```

**Comment by tescophil** [comment]
So, tried a bunch of different ways to install and run this and found a solution.

First uninstall the plugin and certbot

Install the plugin as root, ie. sudo pip3 install certbot-dns-duckdns

Then run the certbot command also as root i.e. certbot <options> ...

When I installed this as a 'normal' user it didn't work, and did not install the python version of certbot with the install. Installing certbot separately produced the original error.

Fantastically useful BTW.., getting certs is far more complex than it should be...

**Comment by infinityofspace** [comment]
Thanks for your feedback.

Your previous installed version of certbot is an old version, where the plugins were used in a slightly different way. This plugin unfortunately has no minimum cerbot version requirement in the current version. To use the plugin with such old versions you have to prefix all command line arguments for the plugin and the authenticator name with the package name "certbot-dns-duckdns" and a colon.

Therefore the argument:
```
--authenticator dns-duckdns
```
 now becomes:
```
--authenticator certbot-dns-duckdns:dns-duckdns
```

Your example is now:

```commandline
certbot certonly \
  --non-interactive \
  --agree-tos \
  --email my-email@gmail.com \
  --preferred-challenges dns \
  --authenticator certbot-dns-duckdns:dns-duckdns \
  --certbot-dns-duckdns:dns-duckdns-token <my-token> \
  --certbot-dns-duckdns:dns-duckdns-propagation-seconds 60 \
  -d "*.my-site.duckdns.org"
```

You can use the following command to check which plugins were found:
```commandline
certbot plugins
```

With the new installation (after removing the exisiting certbot installation) of the plugin with root rights, you had installed a newer version of certbot which has solved this problem.

If you use certbot as root, then you have to install the plugins as root too. The problem relates in the way certbot detects the plugins, because the python side packages are user context dependent and cerbot detects the plugins through setuptools entry points. Certbot also tries to access the paths /etc/letsencrypt/* with default configuration, which is usually only possible with appropriate permissions (i.e. root rights). 

**The easiest solution until I fixed the issue would be, as you already described, to simply install this dns plugin with root rights after removing existing certbot installations.**

An alternative and easy way to get started seems to me a Docker image. The Docker image support is already added in the repo and can be used for a local build of a Docker image. This would also solve the biggest problem with the very different and old versions of certbot from the OS package archives. A prebuild image (preferably for different architectures) in Docker Hub is planned for the next few weeks.

I will adjust the installation instructions according to the root rights characteristic and add a minimum required version for the Python module.
