### ISSUE TITLE
Does requests 2.27 also suffice?

### ISSUE THREAD

**Issue by osirisinferi** [infinityofspace/certbot_dns_duckdns#26]
**Describe the bug**

Not really a bug, but more of a packaging issue. Currently, certbot-dns-duckdns depends on requests **2.26**:

https://github.com/infinityofspace/certbot_dns_duckdns/blob/f2fe5bddf958b055ad25611e4aca32ad631f6d8c/requirements.txt#L2

However, recently Gentoo [has removed requests 2.26.0 from their repository](https://gitweb.gentoo.org/repo/gentoo.git/commit/dev-python/requests?id=676df577ce9ac07480f7d6be702d23367161859b) in favor of 2.27.

**To Reproduce**

* Install Certbot;
* Install certbot-dns-duckdns;
* Have requests 2.26.x available on the system;
* Notice that `certbot plugins` lists the certbot-dns-duckdns plugin;
* Make sure only requests 2.27.x is available on the system;
* Notice that `certbot plugins` doesn't list the certbot-dns-duckdns plugin any longer.

**Expected behavior**

* certbot-dns-duckdns should be available when only requests 2.27.x is available

**Certbot command**

`certbot plugins`

**Versions (please complete the following version information):**
 - certbot: latest from git
 - certbot_dns_duckdns: 0.7.2

**Additional context**

When I change `requests~=2.26.0` to `requests~=2.26` everything works again. Is pinning requests to 2.26 really necessary or does the plugin also work with 2.27.x?

**Comment by osirisinferi** [comment]
Same goes for `dnspython` by the way, Gentoo doesn't package 2.1.0 any longer, currently only 2.2.0. By changing the dependency on `dnspython` from `~=2.1.0` to `~=2.1` everything works again,

**Comment by infinityofspace** [comment]
Sorry for the longer delay.

Thanks for your bug report regarding the outdated packages and the PR #27.

It is correct that some dependencies are outdated or definitely needs a update.
I will create a maintenance release with appropriate version bumps soon. I'm also going to set up dependabot accordingly, which I've been planning for a while but hadn't found the time to do yet, which will make future updates much simpler about this.

However, a general change in the requirements of the semantic version schema must first be carefully checked to see if the feature releases (e.g. `vx.y`) contain breaking changes instead of the much stricter bugfixes/hotfixes (e.g. `vx.y.z`) in violation of the semantic version schema.

**Comment by osirisinferi** [comment]
> However, a general change in the requirements of the semantic version schema must first be carefully checked to see if the feature releases (e.g. `vx.y`) contain breaking changes instead of the much stricter bugfixes/hotfixes (e.g. `vx.y.z`) in violation of the semantic version schema.

Naturally :slightly_smiling_face: I'm packaging this plugin for [Gentoo users](https://github.com/osirisinferi/third-party-certbot-plugins) along with other third party plugins, but I'm not a user of DuckDNS myself. So I can't check if the plugin actually works with more recent minor versions of the dependencies. The only thing my CI workflow checks is if `certbot plugins` runs properly.

But thank you for picking this up :+1:
